### PR TITLE
Ignore invite links to DFeedback

### LINKED ISSUE #131: Bot doesn't allow invites to the Discord Feedback server
**Describe the bug**
Adding an invite to the official Discord Feedback Guild in a comment will result in the bot telling you to not include invites in your comment.

**To Reproduce**
1. Search a suggestion to comment on
2. Make a comment and add https://discord.gg/discord-feedback anywhere in it
3. Send the message

**Expected behavior**
Bot lets the comment go through 

**Screenshots**
https://axolotl.club/MGB7nWCL.png?key=HailTheAxolotlK60Mwe

**Additional context**
I doubt checking every invite for their guild is unnecessary and only allowing the official invite link
to the Discord Feedback Guild in all it's variations (https://discord.gg/discord-feedback, discord.gg/discord-feedback, discordapp.com/invite/discord-feedback) would be the best way to approach this issue.

### PR DESCRIPTION
**Pull request by MoonlightCapital**
closes #131

# Please check the following boxes
> All boxes are required

- [x] I agree to the [Contribution Guidelines](https://github.com/Dougley/MBv2/blob/master/.github/CONTRIBUTING.md) and to the [Code of Conduct](https://github.com/Dougley/MBv2/blob/master/.github/CODE_OF_CONDUCT.md)
- [x] I tested my code and I verified it's working to the best of my ability
- [x] I checked if my code doesn't violate the styleguide with `npm test`

# Describe your pull request

> This allows invites to the Discord Feedback site to be sent through the bot.

**Why is this change needed?**

I felt like doing some contributions to the bot to clean up the backlog of issues.

**Does your pull request solve an open issue? If yes, please mention what one**
closes #131 
> See https://help.github.com/en/articles/closing-issues-using-keywords

immagine

### CODE REVIEW

**Comment by Arzte** [comment]
This should probably include discord testers, as it should also be a valid invite someone could place in a comment

**Comment by Kitty-Therapist** [comment]
@MoonlightCapital Can you include Discord Testers as well if it's not already included?

**Comment by MoonlightCapital** [comment]
Later when I get home.

**Comment by Dougley** [comment]
Stale

**Pull request closed without merging**
